/* The following code was generated by JFlex 1.6.0 */


package Analisis.Haskell;

import Constante.Constante;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>Haskell_Lexico.jflex</tt>
 */
public class Haskell_Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 49, 47, 50, 49, 49,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    49, 25, 48,  0, 14,  0, 26,  5, 15, 16,  3,  1, 39,  2, 46,  4, 
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45,  0, 40, 23, 24, 22,  0, 
     0, 20, 41, 30,  8, 18, 19, 35, 36, 43, 41, 41, 21,  6, 32,  7, 
     9, 12, 13, 42, 10, 17, 34, 41, 33, 41, 41, 28,  0, 29,  0, 44, 
     0, 20, 41, 30,  8, 18, 19, 35, 36, 43, 41, 41, 21,  6, 32,  7, 
     9, 12, 13, 42, 10, 17, 34, 41, 33, 41, 41, 37, 27, 38,  0,  0, 
     0,  0,  0,  0,  0, 50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\5\6"+
    "\1\1\1\6\1\7\1\10\1\11\4\6\1\12\1\13"+
    "\1\14\3\1\1\15\1\16\1\6\1\1\1\17\1\20"+
    "\1\21\1\22\2\6\1\23\1\24\1\1\1\25\4\0"+
    "\1\6\1\0\6\6\1\0\4\6\1\0\2\6\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\6\1\0"+
    "\1\35\2\6\1\35\2\0\1\36\1\37\3\0\1\40"+
    "\2\41\1\0\3\6\1\42\2\6\1\43\1\0\1\6"+
    "\1\0\1\6\1\44\1\6\2\45\1\46\1\6\1\0"+
    "\2\6\1\0\1\43\2\6\1\23\3\0\1\47\1\50"+
    "\1\47\1\6\1\51\1\52\1\53\1\6\2\54\1\0"+
    "\2\6\1\55\1\6\1\55\1\56\1\53\1\56\1\57"+
    "\1\60\1\0\2\6\2\61\2\6\1\62\1\6\2\63"+
    "\1\64\1\6\1\65\1\6\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\63\0\63\0\63\0\231\0\314"+
    "\0\377\0\u0132\0\u0165\0\u0198\0\u01cb\0\u01fe\0\63\0\63"+
    "\0\63\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363"+
    "\0\u0396\0\u03c9\0\u03fc\0\63\0\63\0\u042f\0\u0462\0\63"+
    "\0\63\0\63\0\63\0\u0495\0\u04c8\0\u04fb\0\63\0\u052e"+
    "\0\63\0\u0561\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693"+
    "\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b"+
    "\0\u085e\0\u0891\0\u08c4\0\u08f7\0\u092a\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\u095d\0\u0990\0\63\0\u09c3"+
    "\0\u09f6\0\377\0\u0a29\0\u052e\0\63\0\63\0\u0a5c\0\u0a8f"+
    "\0\u0ac2\0\377\0\63\0\377\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e"+
    "\0\377\0\u0bc1\0\u0bf4\0\63\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0"+
    "\0\377\0\u0cf3\0\63\0\377\0\377\0\u0d26\0\u0d59\0\u0d8c"+
    "\0\u0dbf\0\u0df2\0\377\0\u0e25\0\u0e58\0\u0a29\0\u0e8b\0\u0ebe"+
    "\0\u0ef1\0\63\0\377\0\377\0\u0f24\0\377\0\377\0\63"+
    "\0\u0f57\0\63\0\377\0\u0f8a\0\u0fbd\0\u0ff0\0\63\0\u1023"+
    "\0\377\0\63\0\377\0\377\0\63\0\63\0\u1056\0\u1089"+
    "\0\u10bc\0\63\0\377\0\u10ef\0\u1122\0\63\0\u1155\0\63"+
    "\0\377\0\377\0\u1188\0\377\0\u11bb\0\377";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\11\1\16\1\17\1\20"+
    "\1\21\1\11\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\5\11\1\40\1\41\1\42\1\43\1\11\1\44\1\45"+
    "\1\2\1\46\1\2\1\47\1\50\1\47\65\0\1\51"+
    "\61\0\5\52\1\0\1\53\2\52\1\54\1\52\1\55"+
    "\36\52\1\55\4\52\1\0\3\52\6\0\5\11\1\0"+
    "\2\11\3\0\3\11\1\56\1\11\10\0\1\11\1\57"+
    "\5\11\4\0\2\11\1\60\2\11\13\0\5\11\1\0"+
    "\2\11\3\0\5\11\10\0\1\11\1\0\5\11\4\0"+
    "\5\11\13\0\5\11\1\0\2\11\3\0\1\11\1\61"+
    "\3\11\10\0\1\11\1\0\5\11\4\0\5\11\13\0"+
    "\5\11\1\0\1\11\1\62\3\0\3\11\1\63\1\11"+
    "\10\0\1\11\1\0\5\11\4\0\5\11\13\0\5\11"+
    "\1\0\1\11\1\64\3\0\5\11\10\0\1\11\1\0"+
    "\4\11\1\65\4\0\5\11\26\0\1\66\47\0\5\11"+
    "\1\0\2\11\3\0\1\11\1\67\3\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\13\0\5\11\1\0\2\11"+
    "\3\0\4\11\1\70\10\0\1\11\1\0\1\71\4\11"+
    "\4\0\5\11\13\0\5\11\1\0\2\11\3\0\3\11"+
    "\1\72\1\11\10\0\1\11\1\0\5\11\4\0\5\11"+
    "\13\0\5\11\1\73\2\11\3\0\5\11\10\0\1\11"+
    "\1\0\5\11\4\0\1\11\1\74\3\11\13\0\5\11"+
    "\1\0\2\11\3\0\1\11\1\75\3\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\35\0\1\76\62\0\1\77"+
    "\62\0\1\100\62\0\1\101\1\102\63\0\1\103\63\0"+
    "\1\104\35\0\5\11\1\0\2\11\3\0\3\11\1\105"+
    "\1\11\10\0\1\11\1\0\5\11\4\0\5\11\13\0"+
    "\1\106\14\0\1\107\45\0\5\11\1\0\2\11\3\0"+
    "\1\110\4\11\10\0\1\11\1\0\5\11\4\0\5\11"+
    "\13\0\1\111\4\11\1\0\2\11\3\0\2\11\1\112"+
    "\2\11\10\0\1\11\1\0\5\11\4\0\5\11\62\0"+
    "\1\46\1\113\4\0\57\114\1\0\1\115\2\114\5\0"+
    "\1\116\62\0\1\116\1\0\1\117\60\0\1\116\1\0"+
    "\1\120\60\0\1\116\6\0\1\121\54\0\5\11\1\0"+
    "\2\11\3\0\5\11\10\0\1\11\1\0\1\11\1\122"+
    "\3\11\4\0\5\11\45\0\1\123\30\0\5\11\1\0"+
    "\2\11\3\0\5\11\10\0\1\11\1\0\1\124\4\11"+
    "\4\0\5\11\13\0\5\11\1\125\2\11\3\0\5\11"+
    "\10\0\1\126\1\0\5\11\4\0\1\11\1\127\3\11"+
    "\13\0\1\11\1\130\3\11\1\0\2\11\3\0\5\11"+
    "\10\0\1\11\1\0\5\11\4\0\5\11\13\0\5\11"+
    "\1\0\1\11\1\131\3\0\5\11\10\0\1\11\1\0"+
    "\5\11\4\0\5\11\13\0\5\11\1\0\2\11\3\0"+
    "\1\132\4\11\10\0\1\11\1\0\5\11\4\0\5\11"+
    "\13\0\5\11\1\0\2\11\3\0\1\11\1\133\3\11"+
    "\10\0\1\11\1\0\5\11\4\0\5\11\13\0\1\134"+
    "\27\0\1\135\32\0\5\11\1\0\2\11\3\0\5\11"+
    "\10\0\1\11\1\0\2\11\1\136\2\11\4\0\5\11"+
    "\13\0\5\11\1\137\2\11\3\0\5\11\10\0\1\11"+
    "\1\0\5\11\4\0\1\11\1\140\3\11\13\0\2\11"+
    "\1\141\2\11\1\0\2\11\3\0\5\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\13\0\5\11\1\0\2\11"+
    "\3\0\4\11\1\142\10\0\1\11\1\0\5\11\4\0"+
    "\5\11\43\0\1\143\32\0\5\11\1\0\2\11\3\0"+
    "\5\11\10\0\1\144\1\0\5\11\4\0\5\11\13\0"+
    "\4\11\1\145\1\0\2\11\3\0\5\11\10\0\1\11"+
    "\1\0\1\146\4\11\4\0\5\11\13\0\5\11\1\147"+
    "\2\11\3\0\4\11\1\150\10\0\1\11\1\0\5\11"+
    "\4\0\1\11\1\151\3\11\16\0\1\152\57\0\1\153"+
    "\4\11\1\0\2\11\3\0\5\11\10\0\1\154\1\0"+
    "\5\11\4\0\5\11\13\0\3\11\1\155\1\11\1\0"+
    "\2\11\3\0\5\11\10\0\1\11\1\0\5\11\4\0"+
    "\5\11\62\0\1\156\15\0\1\157\64\0\1\160\65\0"+
    "\1\161\103\0\1\162\32\0\5\11\1\0\2\11\3\0"+
    "\5\11\10\0\1\163\1\0\5\11\4\0\5\11\13\0"+
    "\5\11\1\0\2\11\3\0\5\11\10\0\1\164\1\0"+
    "\5\11\4\0\5\11\13\0\2\11\1\165\2\11\1\0"+
    "\2\11\3\0\5\11\10\0\1\11\1\0\5\11\4\0"+
    "\5\11\13\0\5\11\1\0\2\11\3\0\1\11\1\166"+
    "\3\11\10\0\1\11\1\0\5\11\4\0\5\11\13\0"+
    "\5\11\1\0\2\11\3\0\5\11\10\0\1\11\1\0"+
    "\1\167\4\11\4\0\5\11\43\0\1\170\32\0\5\11"+
    "\1\0\2\11\3\0\1\11\1\171\3\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\27\0\1\172\46\0\5\11"+
    "\1\0\2\11\3\0\1\11\1\173\3\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\13\0\5\11\1\174\2\11"+
    "\3\0\5\11\10\0\1\11\1\0\5\11\4\0\1\11"+
    "\1\175\3\11\13\0\5\11\1\0\2\11\3\0\5\11"+
    "\10\0\1\11\1\0\3\11\1\176\1\11\4\0\5\11"+
    "\27\0\1\177\46\0\5\11\1\0\2\11\3\0\5\11"+
    "\10\0\1\200\1\0\5\11\4\0\5\11\13\0\5\11"+
    "\1\0\2\11\3\0\1\11\1\201\3\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\22\0\1\202\53\0\5\11"+
    "\1\0\2\11\3\0\5\11\10\0\1\203\1\0\5\11"+
    "\4\0\5\11\13\0\5\11\1\0\1\11\1\204\3\0"+
    "\5\11\10\0\1\11\1\0\5\11\4\0\5\11\12\0"+
    "\1\205\62\0\1\206\67\0\1\207\56\0\5\11\1\0"+
    "\2\11\3\0\1\210\4\11\10\0\1\11\1\0\5\11"+
    "\4\0\5\11\13\0\5\11\1\0\1\11\1\211\3\0"+
    "\5\11\10\0\1\11\1\0\5\11\4\0\5\11\27\0"+
    "\1\212\46\0\5\11\1\0\2\11\3\0\1\11\1\213"+
    "\3\11\10\0\1\11\1\0\5\11\4\0\5\11\13\0"+
    "\4\11\1\214\1\0\2\11\3\0\5\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\13\0\5\11\1\0\2\11"+
    "\3\0\1\215\4\11\10\0\1\11\1\0\5\11\4\0"+
    "\5\11\12\0\1\216\63\0\5\11\1\0\2\11\3\0"+
    "\5\11\10\0\1\217\1\0\5\11\4\0\5\11\13\0"+
    "\5\11\1\220\2\11\3\0\5\11\10\0\1\11\1\0"+
    "\5\11\4\0\1\11\1\221\3\11\13\0\5\11\1\0"+
    "\2\11\3\0\5\11\10\0\1\11\1\0\4\11\1\222"+
    "\4\0\5\11\13\0\5\11\1\0\2\11\3\0\4\11"+
    "\1\223\10\0\1\11\1\0\5\11\4\0\5\11\13\0"+
    "\4\11\1\224\1\0\2\11\3\0\5\11\10\0\1\11"+
    "\1\0\5\11\4\0\5\11\13\0\5\11\1\0\2\11"+
    "\3\0\3\11\1\225\1\11\10\0\1\11\1\0\5\11"+
    "\4\0\5\11\13\0\5\11\1\0\1\11\1\226\3\0"+
    "\5\11\10\0\1\11\1\0\5\11\4\0\5\11\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4590];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\3\11\10\1\3\11\12\1\2\11"+
    "\2\1\4\11\3\1\1\11\1\1\1\11\4\0\1\1"+
    "\1\0\6\1\1\0\4\1\1\0\2\1\7\11\1\1"+
    "\1\0\1\11\3\1\2\0\2\11\3\0\1\1\1\11"+
    "\1\1\1\0\6\1\1\11\1\0\1\1\1\0\3\1"+
    "\1\11\3\1\1\0\2\1\1\0\4\1\3\0\1\11"+
    "\5\1\1\11\1\1\1\11\1\1\1\0\2\1\1\11"+
    "\2\1\1\11\2\1\2\11\1\0\2\1\1\11\3\1"+
    "\1\11\1\1\1\11\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Código de usuario


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Haskell_Lexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { String errLex = "Error léxico, caracter irreconocible: '"+yytext()+"' en la línea: "+(yyline+1)+" y columna: "+yycolumn;
        System.out.println(errLex);
          }
        case 55: break;
        case 2: 
          { return new Symbol(sym.TMas, yyline, yycolumn, yytext());
          }
        case 56: break;
        case 3: 
          { return new Symbol(sym.TMenos, yyline, yycolumn, yytext());
          }
        case 57: break;
        case 4: 
          { return new Symbol(sym.TPor, yyline, yycolumn, yytext());
          }
        case 58: break;
        case 5: 
          { return new Symbol(sym.TDivision, yyline, yycolumn, yytext());
          }
        case 59: break;
        case 6: 
          { System.out.println("id"); return new Symbol(sym.Id, yyline, yycolumn, yytext());
          }
        case 60: break;
        case 7: 
          { return new Symbol(sym.TDolar, yyline, yycolumn, yytext());
          }
        case 61: break;
        case 8: 
          { return new Symbol(sym.TParentesis_Abre, yyline, yycolumn, yytext());
          }
        case 62: break;
        case 9: 
          { return new Symbol(sym.TParentesis_Cierra, yyline, yycolumn, yytext());
          }
        case 63: break;
        case 10: 
          { return new Symbol(sym.TMayor, yyline, yycolumn, yytext());
          }
        case 64: break;
        case 11: 
          { return new Symbol(sym.TMenor, yyline, yycolumn, yytext());
          }
        case 65: break;
        case 12: 
          { return new Symbol(sym.TIgual, yyline, yycolumn, yytext());
          }
        case 66: break;
        case 13: 
          { return new Symbol(sym.TCorchete_Abre, yyline, yycolumn, yytext());
          }
        case 67: break;
        case 14: 
          { return new Symbol(sym.TCorchete_Cierra, yyline, yycolumn, yytext());
          }
        case 68: break;
        case 15: 
          { return new Symbol(sym.TLlave_Abre, yyline, yycolumn, yytext());
          }
        case 69: break;
        case 16: 
          { return new Symbol(sym.TLlave_Cierra, yyline, yycolumn, yytext());
          }
        case 70: break;
        case 17: 
          { return new Symbol(sym.TComa, yyline, yycolumn, yytext());
          }
        case 71: break;
        case 18: 
          { return new Symbol(sym.TPuntoyComa, yyline, yycolumn, yytext());
          }
        case 72: break;
        case 19: 
          { return new Symbol(sym.Numero, yyline, yycolumn, yytext());
          }
        case 73: break;
        case 20: 
          { 
          }
        case 74: break;
        case 21: 
          { return new Symbol(sym.TAumento, yyline, yycolumn, yytext());
          }
        case 75: break;
        case 22: 
          { return new Symbol(sym.TMayorIgual, yyline, yycolumn, yytext());
          }
        case 76: break;
        case 23: 
          { return new Symbol(sym.TMenorIgual, yyline, yycolumn, yytext());
          }
        case 77: break;
        case 24: 
          { return new Symbol(sym.TIgualacion, yyline, yycolumn, yytext());
          }
        case 78: break;
        case 25: 
          { return new Symbol(sym.TDiferenciacion, yyline, yycolumn, yytext());
          }
        case 79: break;
        case 26: 
          { return new Symbol(sym.TIndiceLista, yyline, yycolumn, yytext());
          }
        case 80: break;
        case 27: 
          { return new Symbol(sym.TAnd, yyline, yycolumn, yytext());
          }
        case 81: break;
        case 28: 
          { return new Symbol(sym.TOr, yyline, yycolumn, yytext());
          }
        case 82: break;
        case 29: 
          { return new Symbol(sym.TIf, yyline, yycolumn, yytext());
          }
        case 83: break;
        case 30: 
          { return new Symbol(sym.Cadena, yyline, yycolumn, yytext());
          }
        case 84: break;
        case 31: 
          { return new Symbol(sym.Caracter, yyline, yycolumn, yytext());
          }
        case 85: break;
        case 32: 
          { return new Symbol(sym.TMax, yyline, yycolumn, yytext());
          }
        case 86: break;
        case 33: 
          { return new Symbol(sym.TMin, yyline, yycolumn, yytext());
          }
        case 87: break;
        case 34: 
          { return new Symbol(sym.TPar, yyline, yycolumn, yytext());
          }
        case 88: break;
        case 35: 
          { return new Symbol(sym.TSum, yyline, yycolumn, yytext());
          }
        case 89: break;
        case 36: 
          { return new Symbol(sym.TEnd, yyline, yycolumn, yytext());
          }
        case 90: break;
        case 37: 
          { return new Symbol(sym.TAsc, yyline, yycolumn, yytext());
          }
        case 91: break;
        case 38: 
          { return new Symbol(sym.TLet, yyline, yycolumn, yytext());
          }
        case 92: break;
        case 39: 
          { return new Symbol(sym.TDesc, yyline, yycolumn, yytext());
          }
        case 93: break;
        case 40: 
          { return new Symbol(sym.TDecc, yyline, yycolumn, yytext());
          }
        case 94: break;
        case 41: 
          { return new Symbol(sym.TVerdadero, yyline, yycolumn, yytext());
          }
        case 95: break;
        case 42: 
          { return new Symbol(sym.TThen, yyline, yycolumn, yytext());
          }
        case 96: break;
        case 43: 
          { return new Symbol(sym.TSucc, yyline, yycolumn, yytext());
          }
        case 97: break;
        case 44: 
          { return new Symbol(sym.TElse, yyline, yycolumn, yytext());
          }
        case 98: break;
        case 45: 
          { return new Symbol(sym.TCase, yyline, yycolumn, yytext());
          }
        case 99: break;
        case 46: 
          { return new Symbol(sym.TImpr, yyline, yycolumn, yytext());
          }
        case 100: break;
        case 47: 
          { return new Symbol(sym.TModulo, yyline, yycolumn, yytext());
          }
        case 101: break;
        case 48: 
          { return new Symbol(sym.TPotencia, yyline, yycolumn, yytext());
          }
        case 102: break;
        case 49: 
          { return new Symbol(sym.TFalso, yyline, yycolumn, yytext());
          }
        case 103: break;
        case 50: 
          { return new Symbol(sym.TRaiz, yyline, yycolumn, yytext());
          }
        case 104: break;
        case 51: 
          { return new Symbol(sym.TRevers, yyline, yycolumn, yytext());
          }
        case 105: break;
        case 52: 
          { return new Symbol(sym.TLength, yyline, yycolumn, yytext());
          }
        case 106: break;
        case 53: 
          { return new Symbol(sym.TProduct, yyline, yycolumn, yytext());
          }
        case 107: break;
        case 54: 
          { return new Symbol(sym.TCalcular, yyline, yycolumn, yytext());
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
