
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 05 23:35:49 CST 2017
//----------------------------------------------------

package Analisis.Haskell;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAnd = 25;
  public static final int SPACE = 6;
  public static final int ENTER = 7;
  public static final int TLength = 43;
  public static final int TComa = 53;
  public static final int TCorchete_Abre = 28;
  public static final int Id = 2;
  public static final int TMin = 34;
  public static final int TSucc = 32;
  public static final int TProduct = 37;
  public static final int TRevers = 38;
  public static final int TDivision = 11;
  public static final int TElse = 49;
  public static final int TIndiceLista = 45;
  public static final int TOr = 26;
  public static final int TIgual = 27;
  public static final int Booleano = 18;
  public static final int TThen = 48;
  public static final int TPar = 40;
  public static final int TIf = 47;
  public static final int TAsc = 41;
  public static final int TMenorIgual = 22;
  public static final int TIgualacion = 23;
  public static final int TLlave_Cierra = 52;
  public static final int Cadena = 5;
  public static final int EOF = 0;
  public static final int TLet = 30;
  public static final int error = 1;
  public static final int TEnd = 46;
  public static final int TSum = 36;
  public static final int TMayorIgual = 21;
  public static final int TLlave_Abre = 51;
  public static final int TParentesis_Abre = 16;
  public static final int TMenos = 9;
  public static final int TMenor = 20;
  public static final int TCalcular = 31;
  public static final int TImpr = 39;
  public static final int TMax = 35;
  public static final int TModulo = 12;
  public static final int TDesc = 42;
  public static final int TMayor = 19;
  public static final int TCase = 50;
  public static final int TMas = 8;
  public static final int TCorchete_Cierra = 29;
  public static final int TPor = 10;
  public static final int Caracter = 4;
  public static final int TDecc = 33;
  public static final int TRaiz = 14;
  public static final int TParentesis_Cierra = 17;
  public static final int Numero = 3;
  public static final int TDiferenciacion = 24;
  public static final int TDolar = 15;
  public static final int TPotencia = 13;
  public static final int TAumento = 44;
}

