
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 08 08:09:51 CST 2017
//----------------------------------------------------

package Analisis.Haskell;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAnd = 26;
  public static final int SPACE = 6;
  public static final int ENTER = 7;
  public static final int TLength = 44;
  public static final int TComa = 54;
  public static final int TCorchete_Abre = 29;
  public static final int Id = 2;
  public static final int TMin = 35;
  public static final int TSucc = 33;
  public static final int TProduct = 38;
  public static final int TRevers = 39;
  public static final int TDivision = 11;
  public static final int TElse = 50;
  public static final int TPuntoyComa = 55;
  public static final int TIndiceLista = 46;
  public static final int TOr = 27;
  public static final int TIgual = 28;
  public static final int TVerdadero = 19;
  public static final int TThen = 49;
  public static final int TPar = 41;
  public static final int TIf = 48;
  public static final int TAsc = 42;
  public static final int TMenorIgual = 23;
  public static final int TIgualacion = 24;
  public static final int TLlave_Cierra = 53;
  public static final int Cadena = 5;
  public static final int EOF = 0;
  public static final int TLet = 31;
  public static final int error = 1;
  public static final int TEnd = 47;
  public static final int TSum = 37;
  public static final int TMayorIgual = 22;
  public static final int TLlave_Abre = 52;
  public static final int TParentesis_Abre = 16;
  public static final int TMenos = 9;
  public static final int TMenor = 21;
  public static final int TCalcular = 32;
  public static final int TImpr = 40;
  public static final int TMax = 36;
  public static final int TModulo = 12;
  public static final int TDesc = 43;
  public static final int TMayor = 20;
  public static final int TCase = 51;
  public static final int TMas = 8;
  public static final int TCorchete_Cierra = 30;
  public static final int TPor = 10;
  public static final int TFalso = 18;
  public static final int Caracter = 4;
  public static final int TDecc = 34;
  public static final int TRaiz = 14;
  public static final int TParentesis_Cierra = 17;
  public static final int Numero = 3;
  public static final int TDiferenciacion = 25;
  public static final int TDolar = 15;
  public static final int TPotencia = 13;
  public static final int TAumento = 45;
}

