
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 12 13:41:44 CST 2017
//----------------------------------------------------

package Analisis.Haskell;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAnd = 24;
  public static final int TLength = 42;
  public static final int TComa = 52;
  public static final int TCorchete_Abre = 27;
  public static final int Id = 2;
  public static final int TMin = 33;
  public static final int TSucc = 31;
  public static final int TProduct = 36;
  public static final int TRevers = 37;
  public static final int TDivision = 9;
  public static final int TElse = 48;
  public static final int TPuntoyComa = 53;
  public static final int TIndiceLista = 44;
  public static final int TOr = 25;
  public static final int TIgual = 26;
  public static final int TVerdadero = 17;
  public static final int TThen = 47;
  public static final int TPar = 39;
  public static final int TIf = 46;
  public static final int TAsc = 40;
  public static final int TMenorIgual = 21;
  public static final int TIgualacion = 22;
  public static final int TLlave_Cierra = 51;
  public static final int Cadena = 5;
  public static final int EOF = 0;
  public static final int TLet = 29;
  public static final int error = 1;
  public static final int TEnd = 45;
  public static final int TSum = 35;
  public static final int TMayorIgual = 20;
  public static final int TLlave_Abre = 50;
  public static final int TParentesis_Abre = 14;
  public static final int TMenos = 7;
  public static final int TMenor = 19;
  public static final int TCalcular = 30;
  public static final int TImpr = 38;
  public static final int TMax = 34;
  public static final int TModulo = 10;
  public static final int TDesc = 41;
  public static final int TMayor = 18;
  public static final int TCase = 49;
  public static final int TMas = 6;
  public static final int TCorchete_Cierra = 28;
  public static final int TPor = 8;
  public static final int TFalso = 16;
  public static final int Caracter = 4;
  public static final int TDecc = 32;
  public static final int TRaiz = 12;
  public static final int TParentesis_Cierra = 15;
  public static final int Numero = 3;
  public static final int TDosPuntos = 54;
  public static final int TDiferenciacion = 23;
  public static final int TDolar = 13;
  public static final int TPotencia = 11;
  public static final int TAumento = 43;
}

