
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 19 21:23:47 CST 2017
//----------------------------------------------------

package Analisis.Consola;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAnd = 22;
  public static final int TLength = 40;
  public static final int TComa = 46;
  public static final int TCorchete_Abre = 25;
  public static final int Id = 2;
  public static final int TMin = 31;
  public static final int TSucc = 29;
  public static final int TProduct = 34;
  public static final int TRevers = 35;
  public static final int TDivision = 9;
  public static final int TIndiceLista = 42;
  public static final int TOr = 23;
  public static final int TIgual = 24;
  public static final int TPar = 37;
  public static final int TAsc = 38;
  public static final int TMenorIgual = 19;
  public static final int TIgualacion = 20;
  public static final int TLlave_Cierra = 45;
  public static final int Cadena = 5;
  public static final int EOF = 0;
  public static final int TPorcentaje = 43;
  public static final int TLet = 27;
  public static final int error = 1;
  public static final int TSum = 33;
  public static final int TMayorIgual = 18;
  public static final int TLlave_Abre = 44;
  public static final int TParentesis_Abre = 14;
  public static final int TMenos = 7;
  public static final int TMenor = 17;
  public static final int TCalcular = 28;
  public static final int TImpr = 36;
  public static final int TMax = 32;
  public static final int TModulo = 10;
  public static final int TDesc = 39;
  public static final int TMayor = 16;
  public static final int TMas = 6;
  public static final int TCorchete_Cierra = 26;
  public static final int TPor = 8;
  public static final int Caracter = 4;
  public static final int TDecc = 30;
  public static final int TRaiz = 12;
  public static final int TParentesis_Cierra = 15;
  public static final int Numero = 3;
  public static final int TDiferenciacion = 21;
  public static final int TDolar = 13;
  public static final int TPotencia = 11;
  public static final int TAumento = 41;
}

