
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 03 02:07:14 CST 2017
//----------------------------------------------------

package Analisis.Graphik;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TProtegido = 37;
  public static final int TAls = 68;
  public static final int TIgual = 28;
  public static final int TPor = 11;
  public static final int TDivision = 12;
  public static final int TAumento = 14;
  public static final int TLlave_Cierra = 32;
  public static final int TContinuar = 60;
  public static final int TNot = 27;
  public static final int TMenos = 10;
  public static final int TMenor = 19;
  public static final int TInterrogacion = 59;
  public static final int TVar = 34;
  public static final int TParentesis_Cierra = 17;
  public static final int TPrivado = 36;
  public static final int TPotencia = 13;
  public static final int TCorchete_Cierra = 30;
  public static final int TPunto = 69;
  public static final int TDecimal = 65;
  public static final int TPara = 41;
  public static final int TComa = 33;
  public static final int TDisminucion = 15;
  public static final int TGk = 56;
  public static final int TCadena = 63;
  public static final int THereda = 57;
  public static final int Cadena = 6;
  public static final int TCorchete_Abre = 29;
  public static final int TLlamar = 52;
  public static final int TSi = 71;
  public static final int Caracter = 5;
  public static final int TMas = 9;
  public static final int TColumna = 51;
  public static final int TMenorIgual = 21;
  public static final int TImportar = 55;
  public static final int TNuevo = 70;
  public static final int TDatos = 50;
  public static final int TSino = 72;
  public static final int TImprimir = 48;
  public static final int TPublico = 35;
  public static final int TCaso = 39;
  public static final int Id = 2;
  public static final int EOF = 0;
  public static final int TIgualacion = 22;
  public static final int TDiferenciacion = 23;
  public static final int TLlave_Abre = 31;
  public static final int TDosPuntos = 38;
  public static final int TVacio = 64;
  public static final int TMayor = 18;
  public static final int TParentesis_Abre = 16;
  public static final int TGraphikar_Funcion = 49;
  public static final int TIncluye = 54;
  public static final int Falso = 8;
  public static final int TMientras = 74;
  public static final int TInicio = 43;
  public static final int Verdadero = 7;
  public static final int TDefecto = 40;
  public static final int TProcesar = 44;
  public static final int error = 1;
  public static final int TCaracter = 66;
  public static final int TMayorIgual = 20;
  public static final int TTerminar = 61;
  public static final int TAnd = 24;
  public static final int TXor = 26;
  public static final int TBool = 67;
  public static final int TEntero = 62;
  public static final int TDondeTodo = 47;
  public static final int Entero = 3;
  public static final int TLlamarHk = 53;
  public static final int TRetornar = 58;
  public static final int TOr = 25;
  public static final int TDondeCada = 46;
  public static final int THacer = 42;
  public static final int TDonde = 45;
  public static final int Decimal = 4;
  public static final int TSeleccion = 73;
}

